CREATE TABLE CARGO (
    ID                      NUMBER(10) NOT NULL,
    CARGO                   VARCHAR2(255) NOT NULL,
    SALARIO                 FLOAT NOT NULL,
    MODIFICADOR_SALARIO     FLOAT NOT NULL,
    BENEFICIO               FLOAT CONSTRAINT BNF_CHK CHECK (BENEFICIO BETWEEN 0 AND 1),
    PRIMARY KEY (ID)
);

CREATE TABLE FUNCIONARIO (
    ID              NUMBER(10) NOT NULL,
    NOME            VARCHAR(255) NOT NULL,
    ID_CARGO        VARCHAR(255) NOT NULL,
    MES_CONTRATACAO NUMBER(2, 0) NOT NULL,
    ANO_CONTRATACAO NUMBER(4, 0) NOT NULL,
    PRIMARY KEY (ID)
);


CREATE TABLE VENDA (
    ID_FUNCIONARIO  VARCHAR(255) NOT NULL,
    VALOR_VENDA     FLOAT NOT NULL,
    MES_VENDA       NUMBER(2, 0) NOT NULL,
    ANO_VENDA       NUMBER(4, 0) NOT NULL,
    PRIMARY KEY (ID_FUNCIONARIO, MES_VENDA, ANO_VENDA)
);